version: '3.8'

services:
<<<<<<< HEAD
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
=======
  nginx:
    image: nginx:alpine
    container_name: nginx-web-server
    ports:
      - "8080:80"
    volumes:
      - ./src:/usr/share/nginx/html:ro
    restart: unless-stopped
    networks:
      - web-network

networks:
  web-network:
    driver: bridge
>>>>>>> 77b59cccf55c6e7cb2d30316c58af91bf4380ab7
