name: Ejecutar hola_mundo.py

on:
  push:
    branches:
      - main  

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Ejecutar el script
      run: python hola_mundo.py
